name: flutterkhaltipayment
description: An unofficial Khalti SDK that can be used by Khalti merchants to integrate Khalti payment on their flutter apps.
version: 0.4.0
author: BKSAPPS
homepage: https://github.com/spyderbibek/flutter_khalti_payment

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bksapps.flutterkhaltipayment
        pluginClass: FlutterkhaltipaymentPlugin